# Generated by Django 4.1.3 on 2022-11-30 07:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('maiden', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('female', 'FEMALE')], max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('first_payment_date', models.DateField(default=datetime.date(2022, 12, 29), null=True)),
                ('second_payment_date', models.DateField(default=datetime.date(2023, 1, 28), null=True)),
                ('final_payment_date', models.DateField(default=datetime.date(2023, 2, 27), null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile/avatar.svg', upload_to='profile'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('employer_contact', models.CharField(max_length=50)),
                ('debtor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.debtor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('product_sn', models.CharField(max_length=50)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('first_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('second_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('final_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('debtor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.debtor')),
            ],
        ),
        migrations.AddField(
            model_name='debtor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
