# Generated by Django 4.1.3 on 2022-12-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_debtor_notis_alter_debtor_final_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='notis',
        ),
    ]
