# Generated by Django 4.1.3 on 2022-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_debtor_final_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=45),
        ),
        migrations.AlterField(
            model_name='product',
            name='first_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
