# Generated by Django 4.1.3 on 2022-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_final_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='final_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='first_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
