# Generated by Django 4.1.3 on 2022-11-10 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('maiden', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('female', 'FEMALE')], max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=50)),
                ('employer_contact', models.CharField(max_length=50)),
                ('debtor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.debtor')),
            ],
        ),
        migrations.CreateModel(
            name='Prodcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('product_sn', models.CharField(max_length=50)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('first_payment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('second_payment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_payment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('debtor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.debtor')),
            ],
        ),
    ]
