# Generated by Django 4.1.3 on 2022-11-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_final_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
