# Generated by Django 4.1.3 on 2022-11-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_debtor_work_prodcut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodcut',
            new_name='Product',
        ),
    ]
