# Generated by Django 4.1.3 on 2022-12-06 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_product_product_id_remove_work_work_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_fully_paid',
        ),
        migrations.AddField(
            model_name='debtor',
            name='is_fully_paid',
            field=models.CharField(blank=True, default='no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='final_payment_date',
            field=models.DateField(default=datetime.date(2023, 3, 6), null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='first_payment_date',
            field=models.DateField(default=datetime.date(2023, 1, 5), null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='second_payment_date',
            field=models.DateField(default=datetime.date(2023, 2, 4), null=True),
        ),
    ]
