# Generated by Django 4.1.3 on 2022-11-30 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_debtor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='final_payment_date',
            field=models.DateField(default=datetime.date(2023, 2, 28), null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='first_payment_date',
            field=models.DateField(default=datetime.date(2022, 12, 30), null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='second_payment_date',
            field=models.DateField(default=datetime.date(2023, 1, 29), null=True),
        ),
    ]
