# Generated by Django 4.1.3 on 2022-11-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_prodcut_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='maiden',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
