# Generated by Django 4.1.3 on 2022-12-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_product_is_fully_paid_debtor_is_fully_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
