# Generated by Django 4.1.3 on 2022-12-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_debtor_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='id_number',
            field=models.CharField(default='75-473382j67', max_length=14),
            preserve_default=False,
        ),
    ]
