# Generated by Django 4.1.3 on 2022-12-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_debtor_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.CharField(default='core i5 6th generation', max_length=100),
            preserve_default=False,
        ),
    ]
