# Generated by Django 4.1.3 on 2022-11-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_debtor_created_debtor_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='address',
            field=models.CharField(default='176 smurts waterfalls prospects', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='address',
            field=models.CharField(default='65 speke avenue', max_length=50),
            preserve_default=False,
        ),
    ]
