# Generated by Django 4.1.3 on 2022-12-07 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_product_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='id',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='final_payment_date',
            field=models.DateField(default=datetime.date(2023, 3, 7), null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='first_payment_date',
            field=models.DateField(default=datetime.date(2023, 1, 6), null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='second_payment_date',
            field=models.DateField(default=datetime.date(2023, 2, 5), null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='debtor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.debtor'),
        ),
    ]
