# Generated by Django 4.1.3 on 2022-11-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_deposit_alter_product_product_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_fully_paid',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
