# Generated by Django 4.1.3 on 2022-11-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_due_date',
            field=models.DateField(null=True),
        ),
    ]
