# Generated by Django 4.1.3 on 2022-11-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_product_payment_date_product_payment_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='payment_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='payment_due_date',
        ),
    ]
