# Generated by Django 4.1.3 on 2022-11-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_payment_date_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
