# Generated by Django 4.1.3 on 2022-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='first_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
