# Generated by Django 4.1.3 on 2022-11-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_debtor_created_alter_product_first_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
