# Generated by Django 4.1.3 on 2022-11-17 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_product_updated_alter_product_final_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='first_payment_date',
            field=models.DateField(default=datetime.date(2022, 12, 17), null=True),
        ),
    ]
