# Generated by Django 4.1.3 on 2022-11-17 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_debtor_first_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='final_payment_date',
            field=models.DateField(default=datetime.date(2023, 2, 15), null=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='second_payment_date',
            field=models.DateField(default=datetime.date(2023, 1, 16), null=True),
        ),
    ]
