# Generated by Django 4.1.3 on 2022-11-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_debtor_final_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
