# Generated by Django 4.1.3 on 2022-12-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='partial_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
