# Generated by Django 4.1.3 on 2022-12-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notis', '0002_notifications_partial_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created']},
        ),
    ]
